import React from 'react';
import FileUpload from '../components/FileUpload';
// eslint-disable-next-line no-unused-vars
import { motion } from 'framer-motion';
import { Sparkles, Zap, BarChart2 } from 'lucide-react';

const Home = () => {
    return (
        <div className="flex flex-col items-center justify-center min-h-[85vh] gap-12 relative overflow-hidden">
            {/* Background Blobs */}
            <div className="absolute top-[-20%] left-[-10%] w-[500px] h-[500px] bg-purple-300 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-blob"></div>
            <div className="absolute top-[-20%] right-[-10%] w-[500px] h-[500px] bg-indigo-300 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-blob animation-delay-2000"></div>
            <div className="absolute bottom-[-20%] left-[20%] w-[500px] h-[500px] bg-pink-300 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-blob animation-delay-4000"></div>

            <motion.div
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8 }}
                className="text-center space-y-6 max-w-4xl px-4 z-10"
            >
                <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full glass border border-white/40 text-indigo-700 text-sm font-bold mb-4 shadow-sm animate-float">
                    <Sparkles size={16} />
                    <span>AI-Powered Learning Revolution</span>
                </div>
                <h1 className="text-6xl md:text-8xl font-extrabold tracking-tight text-white drop-shadow-sm leading-tight">
                    Study <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 drop-shadow-sm">Smarter</span>, <br />
                    Not Harder.
                </h1>
                <p className="text-xl md:text-2xl text-slate-700 max-w-2xl mx-auto leading-relaxed font-medium">
                    Turn messy notes into mastery. Instant flashcards & quizzes generated by AI.
                </p>
            </motion.div>

            <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: 0.2, duration: 0.5 }}
                className="w-full max-w-3xl z-10"
            >
                <div className="glass-card p-2">
                    <FileUpload />
                </div>
            </motion.div>

            <motion.div
                initial={{ opacity: 0, y: 40 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.4, duration: 0.8 }}
                className="grid grid-cols-1 md:grid-cols-3 gap-6 w-full max-w-6xl px-4 z-10"
            >
                {[
                    {
                        icon: <Sparkles className="w-8 h-8 text-purple-600 mb-2" />,
                        title: 'Instant AI Generation',
                        desc: 'Turn messy PDFs into structured Quizzes in seconds using Llama 3.'
                    },
                    {
                        icon: <Zap className="w-8 h-8 text-amber-500 mb-2" />,
                        title: 'Active Recall',
                        desc: 'Scientific study methods built-in via interactive flashcards.'
                    },
                    {
                        icon: <BarChart2 className="w-8 h-8 text-indigo-500 mb-2" />,
                        title: 'Progress Tracking',
                        desc: 'Save your sessions and watch your knowledge grow over time.'
                    },
                ].map((feature, i) => (
                    <div key={i} className="group glass-card p-8 hover:-translate-y-2 hover:bg-white/60">
                        <div className="w-14 h-14 bg-white/50 rounded-2xl shadow-sm flex items-center justify-center mb-6 border border-white/60 group-hover:scale-110 transition-transform">
                            {feature.icon}
                        </div>
                        <h3 className="text-2xl font-bold text-gray-800 mb-3">{feature.title}</h3>
                        <p className="text-gray-600 leading-relaxed font-medium">{feature.desc}</p>
                    </div>
                ))}
            </motion.div>
        </div>
    );
};

export default Home;
