import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const exportToPDF = (data, type = 'flashcards', title = 'Study Set') => {
    try {
        console.log("Exporting PDF...", { type, dataLength: data?.length });

        if (!data || data.length === 0) {
            alert("No data to export! Please generate flashcards or quiz first.");
            return;
        }

        const doc = new jsPDF();

        // Title
        doc.setFontSize(22);
        doc.setTextColor(79, 70, 229); // Indigo
        doc.text(title, 14, 20);

        // Subtitle
        doc.setFontSize(11);
        doc.setTextColor(100, 100, 100);
        doc.text(`Generated by MindFlow AI - ${new Date().toLocaleDateString()}`, 14, 28);

        // Line separator
        doc.setDrawColor(200, 200, 200);
        doc.line(14, 32, 196, 32);

        if (type === 'flashcards') {
            const tableBody = data.map((card, index) => [
                `Q${index + 1}: ${card.question}`,
                card.answer
            ]);

            autoTable(doc, {
                startY: 38,
                head: [['Question', 'Answer']],
                body: tableBody,
                theme: 'striped',
                styles: {
                    fontSize: 10,
                    cellPadding: 6,
                    overflow: 'linebreak',
                    lineColor: [200, 200, 200]
                },
                headStyles: {
                    fillColor: [79, 70, 229],
                    textColor: 255,
                    fontStyle: 'bold'
                },
                alternateRowStyles: {
                    fillColor: [245, 247, 255]
                },
                columnStyles: {
                    0: { cellWidth: 90, fontStyle: 'bold' },
                    1: { cellWidth: 90 }
                },
            });
        } else if (type === 'quiz') {
            const tableBody = [];

            data.forEach((q, i) => {
                // Question row - using simple ASCII
                tableBody.push([
                    { content: `Question ${i + 1}`, styles: { fontStyle: 'bold', fillColor: [79, 70, 229], textColor: 255 } },
                    { content: q.question, styles: { fontStyle: 'bold', fillColor: [245, 247, 255] } }
                ]);

                // Options - using [X] for correct, [ ] for wrong
                q.options.forEach((opt, idx) => {
                    const isCorrect = idx === q.correctIndex;
                    tableBody.push([
                        { content: isCorrect ? '[X]' : '[ ]', styles: { halign: 'center', textColor: isCorrect ? [34, 139, 34] : [100, 100, 100] } },
                        { content: opt, styles: { textColor: isCorrect ? [34, 139, 34] : [60, 60, 60] } }
                    ]);
                });

                // Explanation
                if (q.explanation) {
                    tableBody.push([
                        { content: 'Why:', styles: { fontStyle: 'italic', textColor: [100, 100, 100] } },
                        { content: q.explanation, styles: { fontStyle: 'italic', textColor: [100, 100, 100] } }
                    ]);
                }

                // Spacer row
                tableBody.push([{ content: '', colSpan: 2, styles: { minCellHeight: 4 } }]);
            });

            autoTable(doc, {
                startY: 38,
                body: tableBody,
                theme: 'plain',
                styles: {
                    fontSize: 10,
                    cellPadding: 4,
                    overflow: 'linebreak'
                },
                columnStyles: {
                    0: { cellWidth: 25 },
                    1: { cellWidth: 160 }
                },
            });
        }

        doc.save(`mindflow-${type}-${Date.now()}.pdf`);
        console.log("PDF saved successfully!");

    } catch (error) {
        console.error("PDF Export Error:", error);
        alert("Failed to export PDF: " + error.message);
    }
};
