import React, { useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Upload,
  FileText,
  Sparkles,
  CheckCircle,
  AlertCircle,
  FileCode,
  ArrowRight,
  ClipboardList,
  Zap,
  BookOpen,
} from 'lucide-react';
import { motion as Motion, AnimatePresence } from 'framer-motion';
import { useStudy } from '../context/StudyContext';

const formatFileSize = (size) => {
  if (!size && size !== 0) return null;
  if (size < 1024) return `${size} B`;
  if (size < 1024 * 1024) return `${Math.round(size / 1024)} KB`;
  return `${(size / (1024 * 1024)).toFixed(1)} MB`;
};

const STAGES = [
  { id: 'parsing', label: 'Extracting & Parsing Document', desc: 'Analyzing key concepts, headings, and structure' },
  { id: 'generating', label: 'AI Flashcard & Quiz Generation', desc: 'Synthesizing spaced-repetition active recall cards' },
  { id: 'ready', label: 'Review Ready', desc: 'Launching interactive study mode automatically' },
];

const SAMPLE_NOTES = [
  {
    title: 'Cellular Respiration & Bioenergetics',
    category: 'Biology 101',
    icon: '🧬',
    text: `Cellular respiration is a set of metabolic reactions and processes that take place in the cells of organisms to convert biochemical energy from nutrients into adenosine triphosphate (ATP). The reactions involved include glycolysis, the transition reaction (pyruvate oxidation), the Krebs cycle (citric acid cycle), and oxidative phosphorylation via the electron transport chain. Glycolysis occurs in the cytoplasm and breaks down glucose into two pyruvate molecules, producing a net gain of 2 ATP and 2 NADH. Pyruvate then enters the mitochondrial matrix where it is converted into Acetyl-CoA. In the Krebs cycle, Acetyl-CoA is combined with oxaloacetate to form citrate, generating ATP, NADH, and FADH2. Finally, the electron transport chain in the inner mitochondrial membrane uses high-energy electrons from NADH and FADH2 to create a proton gradient across the membrane, driving ATP synthase to produce approximately 30 to 32 ATP per glucose molecule. Oxygen acts as the final electron acceptor, combining with protons to form water.`,
  },
  {
    title: 'Data Structures: Binary Trees & Big-O',
    category: 'Computer Science',
    icon: '💻',
    text: `A Binary Search Tree (BST) is a node-based binary tree data structure which has the following properties: the left subtree of a node contains only nodes with keys lesser than the node's key; the right subtree contains only nodes with keys greater than the node's key; and both left and right subtrees must also be binary search trees. Average time complexity for BST operations (Search, Insertion, Deletion) is O(log n), where n is the number of nodes. However, in the worst-case scenario where the tree becomes skewed (unbalanced), operations degrade to O(n). To prevent degradation, self-balancing trees like AVL Trees and Red-Black Trees perform automatic rotations during insertion and deletion to maintain height at O(log n). Inorder traversal of a BST visits nodes in ascending sorted order.`,
  },
  {
    title: 'Electromagnetism & Maxwell Equations',
    category: 'Physics',
    icon: '⚡',
    text: `Maxwell's equations are a set of four fundamental differential equations that describe how electric and magnetic fields are generated and altered by each other and by charges and currents. 1. Gauss's Law states that electric charges produce electric fields and the electric flux through a closed surface is proportional to the enclosed charge. 2. Gauss's Law for Magnetism asserts that there are no magnetic monopoles; the total magnetic flux through a closed surface is zero. 3. Faraday's Law of Induction demonstrates that a time-varying magnetic field induces an electromotive force and electric field. 4. Ampère's Law with Maxwell's addition shows that magnetic fields can be generated by electric currents and by changing electric fields (displacement current). Together, these equations predict the propagation of electromagnetic waves traveling at the speed of light.`,
  },
];

const FileUpload = () => {
  const navigate = useNavigate();
  const {
    handleFileUploadAndGenerate,
    handleGenerate,
    loading,
    uploadStage,
    flashcards,
    error,
    resetUploadStage,
  } = useStudy();

  const fileInputRef = useRef(null);
  const [activeTab, setActiveTab] = useState('upload'); // 'upload' | 'text'
  const [pastedText, setPastedText] = useState('');
  const [isDragging, setIsDragging] = useState(false);
  const [fileMeta, setFileMeta] = useState(null);
  const [generatedCount, setGeneratedCount] = useState(0);

  const processFile = async (file) => {
    setFileMeta({
      name: file.name,
      size: formatFileSize(file.size),
      kind: file.type === 'application/pdf' ? 'PDF' : 'TXT',
    });

    const result = await handleFileUploadAndGenerate(file);
    if (result.ok) {
      setGeneratedCount(result.cardCount || flashcards.length);
      setTimeout(() => navigate('/flashcards'), 600);
    }
  };

  const processTextSubmit = async () => {
    if (!pastedText.trim() || pastedText.trim().length < 20) return;
    setFileMeta({
      name: 'Custom Notes Text',
      size: `${pastedText.length} chars`,
      kind: 'TEXT',
    });

    const result = await handleGenerate(pastedText);
    if (result.ok) {
      setGeneratedCount(result.cardCount || flashcards.length);
      setTimeout(() => navigate('/flashcards'), 600);
    }
  };

  const loadSample = async (sample) => {
    setPastedText(sample.text);
    setActiveTab('text');
    setFileMeta({
      name: `${sample.title}.txt`,
      size: `${sample.text.length} chars`,
      kind: 'SAMPLE',
    });

    const result = await handleGenerate(sample.text);
    if (result.ok) {
      setGeneratedCount(result.cardCount || flashcards.length);
      setTimeout(() => navigate('/flashcards'), 600);
    }
  };

  const isProcessing = loading || uploadStage === 'parsing' || uploadStage === 'generating';
  const isReady = uploadStage === 'ready' && generatedCount > 0;

  return (
    <div className="w-full space-y-6">
      {/* Input Mode Selector Bar */}
      <div className="flex items-center justify-between border-b border-[var(--border)] px-6 pt-5 sm:px-8">
        <div className="flex gap-2">
          <button
            type="button"
            onClick={() => !isProcessing && setActiveTab('upload')}
            className={`relative flex items-center gap-2 px-4 py-2.5 text-sm font-semibold transition-colors ${
              activeTab === 'upload'
                ? 'text-[var(--accent)]'
                : 'text-[var(--text-muted)] hover:text-[var(--text-primary)]'
            }`}
          >
            <Upload size={16} />
            <span>Upload Document</span>
            {activeTab === 'upload' && (
              <Motion.div
                layoutId="activeTabUnderline"
                className="absolute bottom-0 left-0 right-0 h-0.5 bg-[var(--accent)]"
              />
            )}
          </button>

          <button
            type="button"
            onClick={() => !isProcessing && setActiveTab('text')}
            className={`relative flex items-center gap-2 px-4 py-2.5 text-sm font-semibold transition-colors ${
              activeTab === 'text'
                ? 'text-[var(--accent)]'
                : 'text-[var(--text-muted)] hover:text-[var(--text-primary)]'
            }`}
          >
            <ClipboardList size={16} />
            <span>Paste Raw Notes</span>
            {activeTab === 'text' && (
              <Motion.div
                layoutId="activeTabUnderline"
                className="absolute bottom-0 left-0 right-0 h-0.5 bg-[var(--accent)]"
              />
            )}
          </button>
        </div>

        <div className="hidden items-center gap-2 text-xs text-[var(--text-muted)] sm:flex">
          <Zap size={13} className="text-[var(--accent)]" />
          <span>AI Multi-Model Powered</span>
        </div>
      </div>

      <div className="px-6 pb-6 sm:px-8 sm:pb-8">
        <AnimatePresence mode="wait">
          {isProcessing ? (
            <Motion.div
              key="processing"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="flex min-h-[300px] flex-col items-center justify-center rounded-[var(--radius-xl)] border border-[var(--border-accent)] bg-[var(--bg-elevated)] p-8 text-center shadow-[var(--shadow-raised)]"
            >
              <div className="relative mb-6 h-16 w-16">
                <div className="absolute inset-0 rounded-full border-4 border-[var(--border)]" />
                <div className="absolute inset-0 animate-spin rounded-full border-4 border-[var(--accent)] border-t-transparent" />
                <div className="absolute inset-0 flex items-center justify-center text-[var(--accent)]">
                  <Sparkles size={24} className="animate-pulse" />
                </div>
              </div>

              <h3 className="font-heading text-2xl font-bold tracking-tight">
                {uploadStage === 'parsing' ? 'Parsing Document & Context' : 'Synthesizing Master Deck'}
              </h3>

              {fileMeta && (
                <div className="mt-2 inline-flex items-center gap-2 rounded-full border border-[var(--border)] bg-[var(--bg-surface)] px-3 py-1 text-xs font-medium text-[var(--text-secondary)]">
                  <span>{fileMeta.name}</span>
                  <span>·</span>
                  <span className="uppercase text-[var(--accent)]">{fileMeta.kind}</span>
                  <span>·</span>
                  <span>{fileMeta.size}</span>
                </div>
              )}

              <p className="mt-4 max-w-md text-sm leading-relaxed text-[var(--text-secondary)]">
                {uploadStage === 'parsing'
                  ? 'Extracting structured concepts, definitions, and equations from your file…'
                  : 'AI is generating high-yield active recall flashcards and quiz questions. This takes ~15 seconds.'}
              </p>

              {/* Progress Steps Timeline */}
              <div className="mt-8 w-full max-w-md space-y-2.5 text-left">
                {STAGES.map((stage, idx) => {
                  const stageIndex = STAGES.findIndex((item) => item.id === uploadStage);
                  const isDone = idx < stageIndex || uploadStage === 'ready';
                  const isCurrent = stage.id === uploadStage;

                  return (
                    <div
                      key={stage.id}
                      className={`flex items-start gap-3.5 rounded-[var(--radius-lg)] border px-4 py-3 transition-all ${
                        isCurrent
                          ? 'border-[var(--border-accent)] bg-[var(--bg-strong)] text-[var(--accent)]'
                          : isDone
                            ? 'border-[rgba(36,138,61,0.2)] bg-[var(--success-soft)] text-[var(--success)]'
                            : 'border-[var(--border)] bg-[var(--bg-surface)] opacity-50'
                      }`}
                    >
                      <div
                        className={`mt-0.5 flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-full text-xs font-bold ${
                          isDone
                            ? 'bg-[var(--success)] text-white'
                            : isCurrent
                              ? 'bg-[var(--accent)] text-white'
                              : 'bg-[var(--border)] text-[var(--text-muted)]'
                        }`}
                      >
                        {isDone ? '✓' : idx + 1}
                      </div>
                      <div className="min-w-0 flex-1">
                        <div className="font-semibold">{stage.label}</div>
                        <div className="text-xs text-[var(--text-muted)]">{stage.desc}</div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </Motion.div>
          ) : isReady ? (
            <Motion.div
              key="success"
              initial={{ opacity: 0, scale: 0.96 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0 }}
              className="flex min-h-[260px] flex-col items-center justify-center rounded-[var(--radius-xl)] border border-[rgba(36,138,61,0.3)] bg-[var(--success-soft)] p-8 text-center shadow-[var(--shadow-raised)]"
            >
              <div className="flex h-16 w-16 items-center justify-center rounded-full bg-[var(--success)] text-white shadow-lg shadow-[rgba(36,138,61,0.3)]">
                <CheckCircle size={32} />
              </div>
              <h3 className="font-heading mt-6 text-3xl font-bold">{generatedCount} Cards Generated!</h3>
              <p className="mt-2 text-sm text-[var(--text-secondary)]">Opening interactive study environment…</p>
            </Motion.div>
          ) : activeTab === 'upload' ? (
            <Motion.div
              key="uploadTab"
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -6 }}
            >
              {/* Drag and Drop Zone */}
              <div
                className={`group relative flex min-h-[280px] cursor-pointer flex-col items-center justify-center rounded-[var(--radius-xl)] border-2 border-dashed p-8 text-center transition-all ${
                  isDragging
                    ? 'border-[var(--accent)] bg-[var(--bg-strong)] shadow-[0_0_24px_rgba(0,113,227,0.15)] scale-[1.01]'
                    : 'border-[var(--border-strong)] bg-[var(--bg-surface)] hover:border-[var(--accent)] hover:bg-[var(--bg-elevated)]'
                }`}
                onDragOver={(e) => {
                  e.preventDefault();
                  setIsDragging(true);
                }}
                onDragLeave={(e) => {
                  e.preventDefault();
                  setIsDragging(false);
                }}
                onDrop={(e) => {
                  e.preventDefault();
                  setIsDragging(false);
                  if (e.dataTransfer.files?.length) processFile(e.dataTransfer.files[0]);
                }}
                onClick={() => fileInputRef.current?.click()}
              >
                <input
                  ref={fileInputRef}
                  type="file"
                  className="hidden"
                  accept=".pdf,.txt,.md"
                  onChange={(e) => {
                    if (e.target.files?.length) processFile(e.target.files[0]);
                  }}
                />

                <div className="relative mb-5">
                  <div className="flex h-16 w-16 items-center justify-center rounded-2xl border border-[var(--border-accent)] bg-[var(--bg-elevated)] text-[var(--accent)] shadow-[var(--shadow-soft)] transition-transform duration-300 group-hover:scale-110">
                    <Upload size={28} />
                  </div>
                  <div className="absolute -right-1 -top-1 flex h-6 w-6 items-center justify-center rounded-full bg-[var(--accent)] text-white">
                    <Sparkles size={12} />
                  </div>
                </div>

                <div className="inline-flex items-center gap-2 rounded-full border border-[var(--border)] bg-[var(--bg-elevated)] px-3 py-1 text-xs font-semibold text-[var(--accent)]">
                  <span>PDF, TXT or Markdown</span>
                  <span>·</span>
                  <span>Up to 20MB</span>
                </div>

                <h3 className="font-heading mt-4 text-2xl font-bold tracking-tight">
                  Drop your lecture file here
                </h3>
                <p className="mt-2 max-w-md text-sm leading-relaxed text-[var(--text-secondary)]">
                  or <span className="font-semibold text-[var(--accent)] underline underline-offset-4">click to browse</span> from your device. MindFlow automatically extracts text and creates study decks.
                </p>

                <div className="mt-6 flex flex-wrap justify-center gap-4 text-xs text-[var(--text-muted)]">
                  <span className="flex items-center gap-1.5">
                    <FileText size={14} className="text-[var(--accent)]" /> Lecture Slides & Handouts
                  </span>
                  <span className="flex items-center gap-1.5">
                    <FileCode size={14} className="text-[var(--accent)]" /> Markdown & Plain Text
                  </span>
                  <span className="flex items-center gap-1.5">
                    <BookOpen size={14} className="text-[var(--accent)]" /> Syllabi & Textbooks
                  </span>
                </div>
              </div>
            </Motion.div>
          ) : (
            <Motion.div
              key="textTab"
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -6 }}
              className="space-y-4"
            >
              <div className="relative">
                <textarea
                  value={pastedText}
                  onChange={(e) => setPastedText(e.target.value)}
                  placeholder="Paste your lecture notes, chapter summary, or raw study text here... (minimum 20 characters)"
                  rows={8}
                  className="w-full rounded-[var(--radius-xl)] border border-[var(--border-strong)] bg-[var(--bg-surface)] p-4 text-sm font-mono leading-relaxed text-[var(--text-primary)] placeholder-[var(--text-muted)] outline-none transition-all focus:border-[var(--accent)] focus:bg-[var(--bg-elevated)] focus:ring-2 focus:ring-[var(--accent-glow)]"
                />
                <div className="absolute bottom-3 right-4 text-xs text-[var(--text-muted)]">
                  {pastedText.length} characters
                </div>
              </div>

              <div className="flex items-center justify-between">
                <p className="text-xs text-[var(--text-muted)]">
                  Tip: Paste bullet points, definitions, or textbook summaries for optimal AI card generation.
                </p>

                <button
                  type="button"
                  disabled={!pastedText.trim() || pastedText.trim().length < 20}
                  onClick={processTextSubmit}
                  className="flex items-center gap-2 rounded-[var(--radius-md)] bg-[var(--accent)] px-6 py-2.5 text-sm font-semibold text-white transition-transform hover:scale-[1.02] active:scale-[0.98] disabled:opacity-50"
                >
                  <Sparkles size={16} />
                  <span>Generate Deck from Text</span>
                  <ArrowRight size={16} />
                </button>
              </div>
            </Motion.div>
          )}
        </AnimatePresence>

        {/* Try with Sample Notes Section */}
        {!isProcessing && !isReady && (
          <div className="mt-8 border-t border-[var(--border)] pt-6">
            <div className="mb-4 flex items-center justify-between">
              <div>
                <h4 className="text-sm font-bold tracking-tight text-[var(--text-primary)]">
                  Try instant 1-click sample notes
                </h4>
                <p className="text-xs text-[var(--text-muted)]">
                  Don't have a file ready? Test our AI generator with these pre-loaded study topics:
                </p>
              </div>
            </div>

            <div className="grid gap-3 sm:grid-cols-3">
              {SAMPLE_NOTES.map((sample) => (
                <button
                  key={sample.title}
                  type="button"
                  onClick={() => loadSample(sample)}
                  className="group flex flex-col justify-between rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--bg-surface)] p-4 text-left transition-all hover:border-[var(--border-accent)] hover:bg-[var(--bg-elevated)] hover:shadow-[var(--shadow-soft)]"
                >
                  <div>
                    <div className="flex items-center justify-between">
                      <span className="text-xl">{sample.icon}</span>
                      <span className="rounded-full bg-[var(--bg-strong)] px-2 py-0.5 text-[10px] font-semibold text-[var(--accent)]">
                        {sample.category}
                      </span>
                    </div>
                    <h5 className="mt-3 text-xs font-bold text-[var(--text-primary)] group-hover:text-[var(--accent)]">
                      {sample.title}
                    </h5>
                  </div>
                  <div className="mt-3 flex items-center gap-1 text-[11px] font-semibold text-[var(--accent)]">
                    <span>Generate Sample Deck</span>
                    <ArrowRight size={12} className="transition-transform group-hover:translate-x-1" />
                  </div>
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Error Notification */}
        {error && (
          <Motion.div
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            className="mt-6 flex items-start gap-3 rounded-[var(--radius-lg)] border border-[rgba(215,0,21,0.2)] bg-[var(--danger-soft)] p-4 text-sm"
          >
            <AlertCircle size={20} className="mt-0.5 flex-shrink-0 text-[var(--danger)]" />
            <div className="flex-1">
              <span className="font-semibold text-[var(--danger)]">{error}</span>
              <button
                type="button"
                onClick={resetUploadStage}
                className="mt-2 block text-xs font-bold text-[var(--accent)] underline"
              >
                Try again
              </button>
            </div>
          </Motion.div>
        )}
      </div>
    </div>
  );
};

export default FileUpload;
