import React, { useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Upload, FileText, CheckCircle, AlertCircle, ArrowRight, ClipboardList } from 'lucide-react';
import { motion as Motion, AnimatePresence } from 'framer-motion';
import { useStudy } from '../context/StudyContext';

const formatFileSize = (size) => {
  if (!size && size !== 0) return null;
  if (size < 1024) return `${size} B`;
  if (size < 1024 * 1024) return `${Math.round(size / 1024)} KB`;
  return `${(size / (1024 * 1024)).toFixed(1)} MB`;
};

const SAMPLE_NOTES = [
  {
    title: 'Cellular Respiration & Bioenergetics',
    category: 'Biology',
    text: `Cellular respiration is a set of metabolic reactions and processes that take place in the cells of organisms to convert biochemical energy from nutrients into adenosine triphosphate (ATP). The reactions involved include glycolysis, the transition reaction (pyruvate oxidation), the Krebs cycle (citric acid cycle), and oxidative phosphorylation via the electron transport chain. Glycolysis occurs in the cytoplasm and breaks down glucose into two pyruvate molecules, producing a net gain of 2 ATP and 2 NADH. Pyruvate then enters the mitochondrial matrix where it is converted into Acetyl-CoA. In the Krebs cycle, Acetyl-CoA is combined with oxaloacetate to form citrate, generating ATP, NADH, and FADH2. Finally, the electron transport chain in the inner mitochondrial membrane uses high-energy electrons from NADH and FADH2 to create a proton gradient across the membrane, driving ATP synthase to produce approximately 30 to 32 ATP per glucose molecule. Oxygen acts as the final electron acceptor, combining with protons to form water.`,
  },
  {
    title: 'Data Structures: Binary Trees & Big-O',
    category: 'Computer Science',
    text: `A Binary Search Tree (BST) is a node-based binary tree data structure which has the following properties: the left subtree of a node contains only nodes with keys lesser than the node's key; the right subtree contains only nodes with keys greater than the node's key; and both left and right subtrees must also be binary search trees. Average time complexity for BST operations (Search, Insertion, Deletion) is O(log n), where n is the number of nodes. However, in the worst-case scenario where the tree becomes skewed (unbalanced), operations degrade to O(n). To prevent degradation, self-balancing trees like AVL Trees and Red-Black Trees perform automatic rotations during insertion and deletion to maintain height at O(log n). Inorder traversal of a BST visits nodes in ascending sorted order.`,
  },
  {
    title: 'Electromagnetism & Maxwell Equations',
    category: 'Physics',
    text: `Maxwell's equations are a set of four fundamental differential equations that describe how electric and magnetic fields are generated and altered by each other and by charges and currents. 1. Gauss's Law states that electric charges produce electric fields and the electric flux through a closed surface is proportional to the enclosed charge. 2. Gauss's Law for Magnetism asserts that there are no magnetic monopoles; the total magnetic flux through a closed surface is zero. 3. Faraday's Law of Induction demonstrates that a time-varying magnetic field induces an electromotive force and electric field. 4. Ampère's Law with Maxwell's addition shows that magnetic fields can be generated by electric currents and by changing electric fields (displacement current). Together, these equations predict the propagation of electromagnetic waves traveling at the speed of light.`,
  },
];

const FileUpload = () => {
  const navigate = useNavigate();
  const {
    handleFileUploadAndGenerate,
    handleGenerate,
    loading,
    uploadStage,
    flashcards,
    error,
    resetUploadStage,
  } = useStudy();

  const fileInputRef = useRef(null);
  const [activeTab, setActiveTab] = useState('upload'); // 'upload' | 'text'
  const [pastedText, setPastedText] = useState('');
  const [isDragging, setIsDragging] = useState(false);
  const [fileMeta, setFileMeta] = useState(null);
  const [generatedCount, setGeneratedCount] = useState(0);

  const processFile = async (file) => {
    setFileMeta({
      name: file.name,
      size: formatFileSize(file.size),
      kind: file.type === 'application/pdf' ? 'PDF' : 'TXT',
    });

    const result = await handleFileUploadAndGenerate(file);
    if (result.ok) {
      setGeneratedCount(result.cardCount || flashcards.length);
      setTimeout(() => navigate('/flashcards'), 600);
    }
  };

  const processTextSubmit = async () => {
    if (!pastedText.trim() || pastedText.trim().length < 20) return;
    setFileMeta({
      name: 'Pasted Notes',
      size: `${pastedText.length} characters`,
      kind: 'TXT',
    });

    const result = await handleGenerate(pastedText);
    if (result.ok) {
      setGeneratedCount(result.cardCount || flashcards.length);
      setTimeout(() => navigate('/flashcards'), 600);
    }
  };

  const loadSample = async (sample) => {
    setPastedText(sample.text);
    setActiveTab('text');
    setFileMeta({
      name: `${sample.title}.txt`,
      size: `${sample.text.length} characters`,
      kind: 'TXT',
    });

    const result = await handleGenerate(sample.text);
    if (result.ok) {
      setGeneratedCount(result.cardCount || flashcards.length);
      setTimeout(() => navigate('/flashcards'), 600);
    }
  };

  const isProcessing = loading || uploadStage === 'parsing' || uploadStage === 'generating';
  const isReady = uploadStage === 'ready' && generatedCount > 0;

  return (
    <div className="w-full">
      {/* Sleek Tab Headers */}
      <div className="flex border-b border-[var(--border)] px-6 pt-4 sm:px-8">
        <button
          type="button"
          onClick={() => !isProcessing && setActiveTab('upload')}
          className={`flex items-center gap-2 border-b-2 px-4 py-3 text-xs font-semibold uppercase tracking-wider transition-colors ${
            activeTab === 'upload'
              ? 'border-[var(--text-primary)] text-[var(--text-primary)]'
              : 'border-transparent text-[var(--text-muted)] hover:text-[var(--text-secondary)]'
          }`}
        >
          <Upload size={14} />
          <span>Upload File</span>
        </button>

        <button
          type="button"
          onClick={() => !isProcessing && setActiveTab('text')}
          className={`flex items-center gap-2 border-b-2 px-4 py-3 text-xs font-semibold uppercase tracking-wider transition-colors ${
            activeTab === 'text'
              ? 'border-[var(--text-primary)] text-[var(--text-primary)]'
              : 'border-transparent text-[var(--text-muted)] hover:text-[var(--text-secondary)]'
          }`}
        >
          <ClipboardList size={14} />
          <span>Paste Text</span>
        </button>
      </div>

      <div className="p-6 sm:p-8">
        <AnimatePresence mode="wait">
          {isProcessing ? (
            <Motion.div
              key="processing"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex min-h-[220px] flex-col items-center justify-center text-center"
            >
              {/* Minimal Linear Progress Bar */}
              <div className="w-full max-w-sm">
                <div className="mb-3 flex items-center justify-between text-xs text-[var(--text-muted)] font-mono">
                  <span>{uploadStage === 'parsing' ? 'PARSING DOCUMENT' : 'GENERATING FLASHCARDS'}</span>
                  <span>{uploadStage === 'parsing' ? '50%' : '85%'}</span>
                </div>
                <div className="h-1.5 w-full overflow-hidden rounded-full bg-[var(--bg-base)] border border-[var(--border)]">
                  <Motion.div
                    className="h-full bg-[var(--text-primary)] rounded-full"
                    initial={{ width: '10%' }}
                    animate={{ width: uploadStage === 'parsing' ? '50%' : '85%' }}
                    transition={{ duration: 0.5, ease: 'easeInOut' }}
                  />
                </div>
              </div>

              {fileMeta && (
                <div className="mt-4 text-xs text-[var(--text-muted)]">
                  {fileMeta.name} · {fileMeta.size}
                </div>
              )}

              <p className="mt-3 text-xs text-[var(--text-secondary)]">
                {uploadStage === 'parsing'
                  ? 'Extracting structured text from your file...'
                  : 'Synthesizing cards and quiz items...'}
              </p>
            </Motion.div>
          ) : isReady ? (
            <Motion.div
              key="success"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex min-h-[200px] flex-col items-center justify-center text-center"
            >
              <div className="flex h-10 w-10 items-center justify-center rounded-full bg-[var(--success-soft)] text-[var(--success)]">
                <CheckCircle size={20} />
              </div>
              <h3 className="mt-3 text-lg font-bold text-[var(--text-primary)]">
                {generatedCount} cards ready
              </h3>
              <p className="mt-1 text-xs text-[var(--text-muted)]">Opening study mode...</p>
            </Motion.div>
          ) : activeTab === 'upload' ? (
            <Motion.div
              key="uploadTab"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
            >
              {/* Clean Minimal Dropzone */}
              <div
                className={`flex min-h-[220px] cursor-pointer flex-col items-center justify-center rounded-[var(--radius-lg)] border border-dashed p-8 text-center transition-colors ${
                  isDragging
                    ? 'border-[var(--text-primary)] bg-[var(--bg-base)]'
                    : 'border-[var(--border-strong)] bg-[var(--bg-surface)] hover:border-[var(--text-secondary)] hover:bg-[var(--bg-elevated)]'
                }`}
                onDragOver={(e) => {
                  e.preventDefault();
                  setIsDragging(true);
                }}
                onDragLeave={(e) => {
                  e.preventDefault();
                  setIsDragging(false);
                }}
                onDrop={(e) => {
                  e.preventDefault();
                  setIsDragging(false);
                  if (e.dataTransfer.files?.length) processFile(e.dataTransfer.files[0]);
                }}
                onClick={() => fileInputRef.current?.click()}
              >
                <input
                  ref={fileInputRef}
                  type="file"
                  className="hidden"
                  accept=".pdf,.txt,.md"
                  onChange={(e) => {
                    if (e.target.files?.length) processFile(e.target.files[0]);
                  }}
                />

                <div className="mb-4 flex h-10 w-10 items-center justify-center rounded-full border border-[var(--border)] bg-[var(--bg-elevated)] text-[var(--text-secondary)]">
                  <Upload size={18} />
                </div>

                <h3 className="text-sm font-bold text-[var(--text-primary)]">
                  Choose a PDF or TXT file
                </h3>
                <p className="mt-1 text-xs text-[var(--text-muted)]">
                  Drag and drop here or click to browse (up to 20MB)
                </p>
              </div>
            </Motion.div>
          ) : (
            <Motion.div
              key="textTab"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="space-y-4"
            >
              <div className="relative">
                <textarea
                  value={pastedText}
                  onChange={(e) => setPastedText(e.target.value)}
                  placeholder="Paste your lecture notes, summaries, or outline text here..."
                  rows={7}
                  className="w-full rounded-[var(--radius-lg)] border border-[var(--border-strong)] bg-[var(--bg-surface)] p-4 text-xs font-mono leading-relaxed text-[var(--text-primary)] placeholder-[var(--text-muted)] outline-none focus:border-[var(--text-primary)] focus:bg-[var(--bg-elevated)]"
                />
                <div className="absolute bottom-3 right-4 text-[11px] text-[var(--text-muted)] font-mono">
                  {pastedText.length} chars
                </div>
              </div>

              <div className="flex items-center justify-end">
                <button
                  type="button"
                  disabled={!pastedText.trim() || pastedText.trim().length < 20}
                  onClick={processTextSubmit}
                  className="flex items-center gap-2 rounded-[var(--radius-md)] bg-[var(--text-primary)] px-5 py-2 text-xs font-semibold text-[var(--bg-elevated)] transition-opacity hover:opacity-90 disabled:opacity-40"
                >
                  <span>Generate Deck</span>
                  <ArrowRight size={14} />
                </button>
              </div>
            </Motion.div>
          )}
        </AnimatePresence>

        {/* Clean Sample Selector */}
        {!isProcessing && !isReady && (
          <div className="mt-6 border-t border-[var(--border)] pt-5">
            <div className="mb-3 text-[11px] font-semibold uppercase tracking-wider text-[var(--text-muted)]">
              Or try a sample deck:
            </div>
            <div className="flex flex-wrap gap-2">
              {SAMPLE_NOTES.map((sample) => (
                <button
                  key={sample.title}
                  type="button"
                  onClick={() => loadSample(sample)}
                  className="rounded-md border border-[var(--border)] bg-[var(--bg-surface)] px-3 py-1.5 text-xs text-[var(--text-secondary)] transition-colors hover:border-[var(--border-strong)] hover:bg-[var(--bg-elevated)] hover:text-[var(--text-primary)]"
                >
                  {sample.category} — {sample.title.split(':')[0]}
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Error Alert */}
        {error && (
          <Motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="mt-4 flex items-center justify-between rounded-[var(--radius-md)] border border-[rgba(215,0,21,0.2)] bg-[var(--danger-soft)] px-4 py-3 text-xs text-[var(--danger)]"
          >
            <span>{error}</span>
            <button
              type="button"
              onClick={resetUploadStage}
              className="font-semibold underline"
            >
              Try again
            </button>
          </Motion.div>
        )}
      </div>
    </div>
  );
};

export default FileUpload;
